@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant "reusinage noms \nidentificateurs" as RN

participant "Réusinage" as R
participant "Génération Source" as GS
participant "Analyseur Syntaxique" as AS
participant "Réusine Arbre Syntaxique" as RAS
participant "Accompagnateur"    as Ac
participant "Visiteur"    as V
participant "Snake\nto\ncamelCase"    as STCC
RN -> V **: Crée
RN -> R **: Crée
activate R
RN -> R : Programme, Visiteur
R -> AS **: Crée
activate AS
R -> AS : Source programme
R -> AS : Source programme
R <-- AS : Arbre Syntaxique
deactivate AS
R -> RAS **: Crée
activate RAS
R -> RAS : Arbre Syntaxique, Visiteur

RAS -> Ac **: Crée
activate Ac
RAS-> Ac : Arbre Syntaxique, Visiteur

RAS-> Ac : Ajoute Visiteur
RAS-> Ac : Visite arbre "Analyseur Syntaxique"

activate V
loop
Ac -> V : noeud

activate STCC
V -> STCC : nom variable
V <-- STCC : nom variable modifié
Ac <-- V : noeud modifié
deactivate STCC
end
deactivate V

RAS <-- Ac : Arbre Syntaxique modifié
deactivate Ac
R <-- RAS : Arbre Syntaxique modifié
R -> GS ** : Arbre Syntaxique modifié

@enduml